# """empty message

# Revision ID: 52726dfbe324
# Revises: dc3f6b74ed14
# Create Date: 2021-06-21 20:22:43.749353

# """
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = '52726dfbe324'
# down_revision = 'dc3f6b74ed14'
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('board', 'owner',
#                existing_type=sa.VARCHAR(length=200),
#                nullable=True)
#     op.alter_column('board', 'title',
#                existing_type=sa.VARCHAR(length=200),
#                nullable=True)
#     op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=True))
#     op.alter_column('card', 'likes_count',
#                existing_type=sa.INTEGER(),
#                nullable=True,
#                existing_server_default=sa.text('0'))
#     op.alter_column('card', 'message',
#                existing_type=sa.VARCHAR(length=200),
#                nullable=True)
#     op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'card', type_='foreignkey')
#     op.alter_column('card', 'message',
#                existing_type=sa.VARCHAR(length=200),
#                nullable=False)
#     op.alter_column('card', 'likes_count',
#                existing_type=sa.INTEGER(),
#                nullable=False,
#                existing_server_default=sa.text('0'))
#     op.drop_column('card', 'board_id')
#     op.alter_column('board', 'title',
#                existing_type=sa.VARCHAR(length=200),
#                nullable=False)
#     op.alter_column('board', 'owner',
#                existing_type=sa.VARCHAR(length=200),
#                nullable=False)
#     # ### end Alembic commands ###
